---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mastodon-web
  name: mastodon-web
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mastodon-web
  template:
    metadata:
      labels:
        app: mastodon-web
    spec:
      containers:
        - image: ghcr.io/mastodon/mastodon:v4.2.12
          name: mastodon-web
          command:
            - bundle
            - exec
            - puma
            - -C
            - config/puma.rb
          envFrom:
            - secretRef:
                name: mastodon-server
            - secretRef:
                name: mastodon-vapid
            - secretRef:
                name: mastodon-db
            - secretRef:
                name: mastodon-redis
            - secretRef:
                name: mastodon-s3
            - secretRef:
                name: mastodon-smtp
          ports:
            - containerPort: 3000
              name: http-web
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 5
            successThreshold: 1
            timeoutSeconds: 2
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 250m
              memory: 768Mi

---
apiVersion: v1
kind: Service
metadata:
  name: mastodon-web
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: http-web
      nodePort: 30007
  selector:
    app: mastodon-web
  sessionAffinity: None
  type: NodePort
